#!/bin/bash

# Edit this!
GVPP=./gvpp.pl
#GVPP=/usr/bin/gvpp.pl

if [ -z "$1" ]; then
    echo "Usage: $0 [-d] [--pdf] filename"
    exit 1
fi

FILEXT="png"
FNAME=""
while [ -n "$1" ]; do
    if [ "$1" == "-d" ]; then
        GRAPHTYPE="digraph"
    fi
    if [ "$1" == "--pdf" ]; then
        FILEXT="pdf"
    fi
    FNAME="$1"
    shift
done

GRAPHTYPE="$GRAPHTYPE" ./gvpp.pl $FNAME |  neato -T$FILEXT -o $(basename $FNAME .dot).$FILEXT
